### ISSUE TITLE
Deploy failed

### ISSUE THREAD

**Issue by sc0Vu** [sc0Vu/vuethwallet#8]
Url
https://dashboard.heroku.com/apps/vuethwallet/activity/builds/6cb49858-1a4a-470f-a04b-e27c6be03134

Message

    node build/build.js
       
       module.js:472
       throw err;
       ^
       
       Error: Cannot find module 'semver'
       at Function.Module._resolveFilename (module.js:470:15)
       at Function.Module._load (module.js:418:25)
       at Module.require (module.js:498:17)
       at require (internal/module.js:20:19)
       at Object.<anonymous> (/tmp/build_8468a8ae31fda61de9712371e5cd1f48/sc0Vu-vuethwallet-586e2a8/build/check-versions.js:2:14)
       at Module._compile (module.js:571:32)
       at Object.Module._extensions..js (module.js:580:10)
       at Module.load (module.js:488:32)
       at tryModuleLoad (module.js:447:12)
       at Function.Module._load (module.js:439:3)
       
       npm ERR! Linux 3.13.0-128-generic
       npm ERR! argv "/tmp/build_8468a8ae31fda61de9712371e5cd1f48/sc0Vu-vuethwallet-586e2a8/.heroku/node/bin/node" "/tmp/build_8468a8ae31fda61de9712371e5cd1f48/sc0Vu-vuethwallet-586e2a8/.heroku/node/bin/npm" "run" "build"
       npm ERR! node v7.10.1
       npm ERR! npm  v4.2.0
       npm ERR! code ELIFECYCLE
       npm ERR! errno 1
       npm ERR! vuethwallet@1.0.0 build: `node build/build.js`
       npm ERR! Exit status 1
       npm ERR!
       npm ERR! Failed at the vuethwallet@1.0.0 build script 'node build/build.js'.
       npm ERR! Make sure you have the latest version of node.js and npm installed.
       npm ERR! If you do, this is most likely a problem with the vuethwallet package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     node build/build.js
       npm ERR! You can get information on how to open an issue for this project with:
       npm ERR!     npm bugs vuethwallet
       npm ERR! Or if that isn't available, you can get their info via:
       npm ERR!     npm owner ls vuethwallet
       npm ERR! There is likely additional logging output above.
       
       npm ERR! Please include the following file with any support request:
       npm ERR!     /app/.npm/_logs/2017-09-19T08_47_04_434Z-debug.log
       
       npm ERR! Linux 3.13.0-128-generic
       npm ERR! argv "/tmp/build_8468a8ae31fda61de9712371e5cd1f48/sc0Vu-vuethwallet-586e2a8/.heroku/node/bin/node" "/tmp/build_8468a8ae31fda61de9712371e5cd1f48/sc0Vu-vuethwallet-586e2a8/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build_8468a8ae31fda61de9712371e5cd1f48/sc0Vu-vuethwallet-586e2a8/.npmrc"
       npm ERR! node v7.10.1
       npm ERR! npm  v4.2.0
       npm ERR! code ELIFECYCLE
       npm ERR! errno 1
       npm ERR! vuethwallet@1.0.0 postinstall: `npm run build`
       npm ERR! Exit status 1
       npm ERR!
       npm ERR! Failed at the vuethwallet@1.0.0 postinstall script 'npm run build'.
       npm ERR! Make sure you have the latest version of node.js and npm installed.
       npm ERR! If you do, this is most likely a problem with the vuethwallet package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     npm run build
       npm ERR! You can get information on how to open an issue for this project with:
       npm ERR!     npm bugs vuethwallet
       npm ERR! Or if that isn't available, you can get their info via:
       npm ERR!     npm owner ls vuethwallet
       npm ERR! There is likely additional logging output above.
       
       npm ERR! Please include the following file with any support request:
       npm ERR!     /app/.npm/_logs/2017-09-19T08_47_04_464Z-debug.log

**Comment by sc0Vu** [comment]
Using [build(]https://github.com/sc0Vu/vuethwallet/tree/build) to deploy.
